site_name: influx-ts-editor V1.3.x Documentation
plugins:
    - search
    - mike
theme:
  name: material
  favicon: img/favicon.ico
  features:
    - content.code.copy

not_in_nav: |

nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - Release Notes: release_notes.md
  - Features: features.md
  - Usage: usage.md
  


